# **Fraud Credit Card Transaction**

# Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing The dataset

In [2]:
dataset = pd.read_csv('/content/creditcard.csv')

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192217 entries, 0 to 192216
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    192217 non-null  float64
 1   V1      192217 non-null  float64
 2   V2      192217 non-null  float64
 3   V3      192217 non-null  float64
 4   V4      192216 non-null  float64
 5   V5      192216 non-null  float64
 6   V6      192216 non-null  float64
 7   V7      192216 non-null  float64
 8   V8      192216 non-null  float64
 9   V9      192216 non-null  float64
 10  V10     192216 non-null  float64
 11  V11     192216 non-null  float64
 12  V12     192216 non-null  float64
 13  V13     192216 non-null  float64
 14  V14     192216 non-null  float64
 15  V15     192216 non-null  float64
 16  V16     192216 non-null  float64
 17  V17     192216 non-null  float64
 18  V18     192216 non-null  float64
 19  V19     192216 non-null  float64
 20  V20     192216 non-null  float64
 21  V21     192216 non-null  float64
 22  V22     192216 non-null  float64
 23  V23     192216 non-null  float64
 24  V24     192216 non-null  float64
 25  V25     192216 non-null  float64
 26  V26     192216 non-null  float64
 27  V27     192216 non-null  float64
 28  V28     192216 non-null  float64
 29  Amount  192216 non-null  float64
 30  Class   192216 non-null  float64
dtypes: float64(31)
memory usage: 45.5 MB

In [4]:
dataset['Class'].value_counts()

0.0    191839
1.0       377
Name: Class, dtype: int64

# Dataset is highly unbalanced

0 -> Normal,

1 -> Fraud

In [5]:
true = dataset[dataset.Class==0]
false = dataset[dataset.Class==1]

In [6]:
true

            Time        V1        V2  ...       V28  Amount  Class
0            0.0 -1.359807 -0.072781  ... -0.021053  149.62    0.0
1            0.0  1.191857  0.266151  ...  0.014724    2.69    0.0
2            1.0 -1.358354 -1.340163  ... -0.059752  378.66    0.0
3            1.0 -0.966272 -0.185226  ...  0.061458  123.50    0.0
4            2.0 -1.158233  0.877737  ...  0.215153   69.99    0.0
...          ...       ...       ...  ...       ...     ...    ...
192211  129590.0  0.182249  1.386223  ... -0.376853    3.94    0.0
192212  129590.0  0.071629  0.968483  ...  0.194947   12.40    0.0
192213  129590.0 -0.353295  0.673990  ...  0.166408   13.31    0.0
192214  129592.0 -1.066013  0.216774  ...  0.087276   19.95    0.0
192215  129593.0  1.925192 -1.754864  ... -0.035390  105.00    0.0

[191839 rows x 31 columns]

In [7]:
false

            Time        V1        V2  ...       V28  Amount  Class
541        406.0 -2.312227  1.951992  ... -0.143276    0.00    1.0
623        472.0 -3.043541 -3.157307  ...  0.035764  529.00    1.0
4920      4462.0 -2.303350  1.759247  ... -0.153029  239.93    1.0
6108      6986.0 -4.397974  1.358367  ...  0.849573   59.00    1.0
6329      7519.0  1.234235  3.019740  ...  0.146793    1.00    1.0
...          ...       ...       ...  ...       ...     ...    ...
191074  129095.0 -1.836940 -1.646764  ...  0.370450  720.80    1.0
191267  129186.0  0.290155  0.049243  ...  0.168233    7.18    1.0
191359  129222.0  1.177824  2.487103  ...  0.268421    4.87    1.0
191544  129308.0  0.054682  1.856500  ...  0.110698   80.90    1.0
191690  129371.0  1.183931  3.057250  ...  0.323740    0.00    1.0

[377 rows x 31 columns]

In [8]:
print(true.shape)
print(false.shape)

(191839, 31)
(377, 31)

In [9]:
true.Amount.describe()

count    191839.000000
mean         89.345488
std         248.537176
min           0.000000
25%           5.990000
50%          22.890000
75%          79.000000
max       19656.530000
Name: Amount, dtype: float64

In [10]:
false.Amount.describe()

count     377.000000
mean      115.954218
std       247.741483
min         0.000000
25%         1.000000
50%        11.400000
75%       104.000000
max      2125.870000
Name: Amount, dtype: float64

# To balance the dataset let us make a same number of true transactions.

In [11]:
true_sample = true.sample(n = 492)
new_dataset = pd.concat([true_sample, false], axis=0)

In [12]:
new_dataset

            Time        V1        V2  ...       V28  Amount  Class
182786  125547.0  1.856412 -0.169252  ... -0.050761   29.61    0.0
18431    29493.0  1.179180  0.084539  ...  0.017116    8.99    0.0
59406    48823.0 -1.728552  3.558601  ...  0.152905    1.90    0.0
20650    31183.0 -0.237191  0.951912  ... -0.020185    8.85    0.0
59494    48865.0  1.438922 -1.188090  ...  0.002135   10.00    0.0
...          ...       ...       ...  ...       ...     ...    ...
191074  129095.0 -1.836940 -1.646764  ...  0.370450  720.80    1.0
191267  129186.0  0.290155  0.049243  ...  0.168233    7.18    1.0
191359  129222.0  1.177824  2.487103  ...  0.268421    4.87    1.0
191544  129308.0  0.054682  1.856500  ...  0.110698   80.90    1.0
191690  129371.0  1.183931  3.057250  ...  0.323740    0.00    1.0

[869 rows x 31 columns]

In [13]:
new_dataset['Class'].value_counts()

0.0    492
1.0    377
Name: Class, dtype: int64

In [14]:
X = new_dataset.iloc[:, :-1].values
y = new_dataset.iloc[:, -1].values

# Spliting dataset into training set and test set

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X , y , test_size = 0.2 , random_state = 2)

In [16]:
print(X.shape, X_test.shape, X_train.shape)

(869, 30) (174, 30) (695, 30)

# Apply Logistic Regression

In [17]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

# Predicting Test set result

In [18]:
y_pred = classifier.predict(X_test)

In [19]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

# Confusion matrix and Accuracy Score

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)*100

[[92  4]
 [ 4 74]]

95.40229885057471